document.writeln("<div id=\'header\' data-trout-elder-style-src=\'https://www.shanghai.gov.cn/assets2020/css/ageing.css\'>");
document.writeln("        <div id=\'skip\'>");
document.writeln("          <a id=\'accesshelp\' title=\'新窗口打开无障碍操作说明页面\' href=\'https://voice.ewdcloud.com/wzagjt/shuoming.html\' target=\'_blank\'>无障碍操作说明</a>");
document.writeln("          <a href=\"javascript:createNodeDiv(\'mainNav\',\'已定位到网站导航\');\" title=\'跳转到网站导航区\'>跳转到网站导航区</a>");
document.writeln("          <a href=\"javascript:createNodeDiv(\'main\',\'已定位到主要内容区域\');\" title=\'跳转到主要内容区域\'>跳转到主要内容区域</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'top-naver\'>");
document.writeln("          <div class=\'contain clearfix\'>");
document.writeln("            <div class=\'header-lt\' id=\'login\'>");
document.writeln("                  <a href=\'https://zwdt.sh.gov.cn/govPortals/index.do\' title=\'一网通办\' class=\'logo-inder\' target=\'_blank\'>");
document.writeln("                     <img src=\'images/icon6.png\' title=\'Hydro Guard\' alt=\'\'></a>");
document.writeln("                  <span id=\'sign\'>");
document.writeln("                    <a href=\'javascript:void(0)\' id=\'dl\' title=\'登录\'>登录</a><a href=\'https://zwdtuser.sh.gov.cn/uc/register/register.html?kind=0\' title=\'注册\'>注册</a>");
document.writeln("                    <a class=\'visible-xs-block\' href=\'javascript:void(0)\' id=\'cniil_wza\' title=\'关怀版\'>关怀版</a>");
document.writeln("                  </span>");
document.writeln("            </div>");
document.writeln("            <div class=\'header-rt\'>");
document.writeln("                <ul class=\'Senior-edition\' id=\'wzazzb\'>");
document.writeln("                  <li id=\'wzagjt\'>");
document.writeln("                    <a href=\'javascript:void(0)\' id=\'cniil_wza\' title=\'网页无障碍辅助工具条，读屏软件用户请忽略。\'>无障碍</a>");
document.writeln("                  </li>");
document.writeln("                  <li id=\'zzb\' style=\'display:none;\'><a href=\'https://www.shanghai.gov.cn/zzzb/index.html?siteId=1\' title=\'长者版\' target=\'_blank\'>长者版</a></li>");
document.writeln("                  <li id=\'ghb\'><a style=\'cursor:pointer;\' id=\'slb\' title=\'关怀版\'>关怀版</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'head\'>");
document.writeln("          <div class=\'xaunfu-header hidden-xs\'>");
document.writeln("            <div class=\'contain clearfix\'>");
document.writeln("              <div class=\'navbar navbar-default index-nav trout-region-nav\' id=\'mainNav\' role=\'navigation\'>");
document.writeln("                <div id=\'mobile-navigation\'>");
document.writeln("                  <ul class=\'nav navbar-nav\'>");
document.writeln("                    <li id=\'nav01\' class=\'dropdown\'>");
document.writeln("                      <a href=\'https://www.shanghai.gov.cn\' class=\'dropdown-toggle\' title=\'首页\'>首页</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'dropdown\'>");
document.writeln("                <a href=\'https://zwdt.sh.gov.cn/govPortals\' class=\'dropdown-toggle\' title=\'监测平台\'>监测平台</a>");
document.writeln("                    </li>");
document.writeln("                    <li id=\'nav02\' class=\'dropdown\'>");
document.writeln("                      <a href=\'https://www.shanghai.gov.cn/nw2315/index.html\' class=\'dropdown-toggle\' title=\'数据中心\'>数据中心</a>");
document.writeln("                    </li>");
document.writeln("                    <li id=\'nav03\' class=\'dropdown\'>");
document.writeln("                      <a href=\'https://www.shanghai.gov.cn/nw2319/index.html\' class=\'dropdown-toggle\' title=\'智能预测\'>智能预测</a>");
document.writeln("                    </li>");
document.writeln("                    <li id=\'nav04\' class=\'dropdown\'>");
document.writeln("                      <a href=\'https://www.shanghai.gov.cn/nw38605/index.html\' class=\'dropdown-toggle\' title=\'应急响应\'>应急响应</a>");
document.writeln("                    </li>");
document.writeln("                    <li id=\'nav05\' class=\'dropdown\'>");
document.writeln("                      <a href=\'https://www.shanghai.gov.cn/nw2318/index.html\' class=\'dropdown-toggle\' title=\'气候要闻\'>气候要闻</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'dropdown email-dengl\'>");
document.writeln("                      <a href=\'https://mail.shanghai.gov.cn/\' class=\'dropdown-toggle\' title=\'邮箱登录\'><span>邮箱登录</span></a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'dropdown email-dengl\'>");
document.writeln("                      <a href=\'http://english.shanghai.gov.cn/nw46669/index.html\' class=\'dropdown-toggle\' title=\'English\'><span>English</span></a>");
document.writeln("                    </li>");
document.writeln("                  </ul>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'contain clearfix\'>");
document.writeln("            <div class=\'midd-top\'>");
document.writeln("              <h2>HydroGuard 基于AIoT的水文测控与洪涝预警综合治理平台</h2>");
document.writeln("              <p>全面感知 · 智能计算 · 快速响应 · 服务社会</p>");
document.writeln("              <div class=\'sousuo trout-region-mutual\' id=\'search\'>");
document.writeln("                          <form accept-charset=\'utf-8\' method=\'post\' action=\'https://search.sh.gov.cn/search\' id=\'searchForm\'  target=\'_blank\'  onsubmit=\'document.charset=\'utf-8\'\'>");
document.writeln("                <div class=\'input\'>");
document.writeln("                  <div class=\'picker\'>");
document.writeln("                    <select id=\'siteId\'  name=\'siteId\'>");
document.writeln("                    	<option title=\'本站\' value=\'www.shanghai.gov.cn\'>本站</option>");
document.writeln("                    	<option title=\'站群\' value=\'all\'>站群</option>");
document.writeln("                    </select>");
document.writeln("                  </div>");
document.writeln("                  <input type=\'text\' title=\'搜索您想了解的政策/资讯/服务\' placeholder=\'搜索您想了解的政策/资讯/服务\' autocomplete=\'off\' id=\'search-input\' name=\'text\'>");
document.writeln("                                  <input id=\'siteId1\'  title=\'搜索\' name=\'siteId1\' type=\'hidden\' value=\'all\'>");
document.writeln("<a href=\'javascript:void(0)\' title=\'语音搜索\'><i id=\'voice-status\' class=\'voice-microphone\'></i></a>");
document.writeln("                </div>");
document.writeln("                <button id=\'searchBtn\' title=\'搜一下\' class=\'search\' type=\'image\'>搜一下</button>");
document.writeln("              </form>");
document.writeln("<div class=\'search-log\' id=\'my-search-log\'>");
document.writeln("                <div id=\'searchHistoryDiv\'></div>");
document.writeln("                <div class=\'log-title\'>热门搜索</div>");
document.writeln("                <div class=\'hot-search\' id=\'hotSearchDiv\'>");
document.writeln("                </div>");
document.writeln("                <ul class=\'department clearfix\' id=\'hotSearchUl\'>");
document.writeln("                </ul>");
document.writeln("              </div>");
document.writeln("                <div id=\'word\'></div>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'https://www.shanghai.gov.cn/voice/css/custom.css\'>");